apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: <Password>
    access: proxy
    editable: true
    isDefault: true
    url: http://fileserver:8086
    jsonData:
      version: Flux
      organization: home
      defaultBucket: influx_mqtt
      tlsSkipVerify: true
    secureJsonFields:
      basicAuthPassword: true
    secureJsonData:
      token: "<TOKEN>"